name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Build Projects
      run: dotnet build EsApiProjectsSampleApp/EsApiProjectsSampleApp/EsApiProjectsSampleApp.csproj
    - name: Build Schedules
      run: dotnet build EsApi4DScheduleServiceSampleApp/EsApi4DScheduleSampleApp/EsApi4DScheduleSampleApp.csproj
